<a href="https://colab.research.google.com/github/AQuaMaRIne307/PythonGCF/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install fpdf

  Preparing metadata (setup.py) ... done
  Created wheel for fpdf: filename=fpdf-1.7.2-py2.py3-none-any.whl size=40704 sha256=f14903ac84066d7ef5078e2595af8b08a4b2490a05b59c08aac3db225fd1f6bf
  Stored in directory: /root/.cache/pip/wheels/65/4f/66/bbda9866da446a72e206d6484cd97381cbc7859a7068541c36
Successfully built fpdf


In [ ]:
!pip install numpy

In [ ]:
import numpy as np

#Create a 1D array
a = np.array([1, 2, 3])

#Create a 2D array
b = np.array([[1, 2], [3, 4]])

#Print the shape of the arrays
print(a.shape)
print(b.shape)

#Print the data type of the 2D array
print(b.dtype)

(3,)
(2, 2)
int64


In [ ]:
print(np.zeros((3,)))
print(np.ones((3,)))
print(np.eye(3))
print(np.arange(1,10,2))
print(np.linspace(0,1,5))
#Array manipulation
a = np.array([[1, 2, 3], [4, 5, 6]])
#Indexing and Slicing
print(a[0, 1])
print(a[:, 1])
print(a[1, :])
#Reshape & Flatten
print(a.reshape(3,2))
print(a.flatten())

[0. 0. 0.]
[1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]
2
[2 5]
[4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
